spring:
  application:
    name: ticho-rainbow
  profiles:
    active: dev
server:
  port: 5122

jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndTripleDES