spring:
  application:
    name: ticho-rainbow
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      resolve-lazily: true
      file-size-threshold: 0
      max-file-size: 100MB
      max-request-size: 100MB



server:
  port: 5122
  undertow:
    buffer-size: 1024
  netty:
    connection-timeout: 60s


jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndTripleDES