ticho:
  async:
    enable-async: true
    thread-name-prefix: Rainbow-
  datasource:
    url: jdbc:mysql://192.168.243.138:10030/ticho_rainbow?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowMultiQueries=true
    username: ENC(8yUwi7gFsHhtfKcuEHa6Kg==)
    password: ENC(7xqTr9Bm6d2RCeaWdwMGlugy9f3P9sAK)
    driver-class-name: com.mysql.cj.jdbc.Driver
    log:
      enable: true
      print-sql: true
      print-simple: true
  security:
    ant-patterns:
      - /
      - /health
      - /**/user/token
      - /**/user/refreshToken
      - /doc.html
      - /swagger-resources/**
      - /webjars/**
      - /v2/api-docs
      - /favicon.ico
      - ${ticho.rainbow.file.mvc-resource-path}
  cors:
    enable: true
  intranet:
    server:
      port: 5120
      sslEnable: false
      sslPort: 5443
      sslPath:
      sslPassword:
      maxRequests:
      maxBindPorts:
  log:
    enable: true
    print: false
  swagger:
    enable: true
  mail:
    enable: true
    # 配置 SMTP 服务器地址
    host: ENC(KaLsKm7W9pkoyWkfAfZyczaZOtVGvYjE)
    # SMTP 服务器的端口
    port: 587
    # 配置邮箱用户名
    username: ENC(MEtHRUmgiDUB5WbRcSeyNdlhcDN2qNx1b2qdhhabHM4=)
    # 配置密码，注意，不是真正的密码，而是申请到的授权码
    password: ENC(smiBr2v3UplE9o4Z2w36s3w5gQrw7D/wqh4HSc1tPU4=)
    # 发件人名称
    sender-name: Rainbow
    # 默认的邮件编码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
        mail.smtp.connectiontimeout: 5000
        # 配饰 SSL 加密工厂
        socketFactoryClass: javax.net.ssl.SSLSocketFactory
        # 表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: false
  rainbow:
    file:
      domain: http://localhost:5122
      mvc-resource-path: /static/file/**
      max-file-size: 20MB
      max-part-size: 10MB
      max-big-file-size: 1GB

spring:
  quartz:
      # 任务存储类型
      job-store-type: memory
      # 关闭时等待任务完成
      wait-for-jobs-to-complete-on-shutdown: false
      # 是否覆盖已有的任务
      overwrite-existing-jobs: true
      # 是否自动启动计划程序
      auto-startup: true
      # 延迟启动
      startup-delay: 0s
      properties:
        org:
          quartz:
            scheduler:
              # 调度器实例名称
              instanceName: RainbowTask
            # 线程池配置
            threadPool:
              class: org.quartz.simpl.SimpleThreadPool
              threadCount: 10
              threadPriority: 5
              threadsInheritContextClassLoaderOfInitializingThread: true
  flyway:
    # 开启 flyway
    enabled: true
    # 是否禁用数据库清理
    clean-disabled: true
    # SQL 迁移的编码
    encoding: UTF-8
    # 是否在执行迁移时自动调用验证。
    validate-on-migrate: true
    # 迁移时发现目标schema非空，而且带有没有元数据的表时，是否自动执行基准迁移，默认false.
    baseline-on-migrate: true

