ticho:
  async:
    enable-async: true
    thread-name-prefix: Rainbow-
  datasource:
    url: ENC(1/d6Y0rrGcknVxFMtf3GlMnw2IBvleJbToH0qXkQ/HrVEX2dmxLCfJVO156SKZ5/90F0QVCpW/zi3Yoj3WC8aZTiOvtu5XuMZIwJh80hQ0noELlnCfxFlvIx5Dd2epG4Bj5bvlOqKzA01buQKpl/ZR8qgKXRbJ+L6YICCcZkOT6wE2mFlOeNdwu+HfPmSgybZuWT+4HHQnV0aVjZGDvqXPdwuHvZJaliadbFTZFe9Ezt8fvGKn4KRnWeZzP/XxT/UYUciHX/K2aqdPS0E1x5kxUmRTji6WlsO3vjEgVdCpHDs8qa2acnIgKlvQUZULZidh96GseEnlyOnSzujt7T24jzzkZin6zJCCLe7JY7fsA=)
    username: ENC(OQHWicNP2vKtZXsHL895SA==)
    password: ENC(D1IEXGr1w4AZNqQGvNz4aPhb1YViyeVT)
    driver-class-name: com.mysql.cj.jdbc.Driver
    log:
      enable: true
      print-sql: true
      print-simple: false
      show-params: true
  security:
    ant-patterns:
      - /
      - /health
      - ${ticho.rainbow.file.mvc-resource-path}
  cors:
    enable: true
  intranet:
    server:
      port: 5120
      sslEnable: false
      sslPort: 5443
      sslPath:
      sslPassword:
      maxRequests:
      maxBindPorts:
  log:
    enable: true
    print: true
  mail:
    enable: true
    # 配置 SMTP 服务器地址
    host: ENC(KaLsKm7W9pkoyWkfAfZyczaZOtVGvYjE)
    # SMTP 服务器的端口
    port: 587
    # 配置邮箱用户名
    username: ENC(MEtHRUmgiDUB5WbRcSeyNdlhcDN2qNx1b2qdhhabHM4=)
    # 配置密码，注意，不是真正的密码，而是申请到的授权码
    password: ENC(5/i5hSsiLT3CnzPn8HAQueEVSSxghAAQOsVOuAVhfX4=)
    # 发件人名称
    sender-name: Rainbow
    # 默认的邮件编码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          # 表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
          debug: false
          connectiontimeout: 5000
          starttls:
            enable: true
            required: true

  cache:
    enable: true
  rainbow:
    security:
      key: ticho
    file:
      domain: http://localhost:5122
      mvc-resource-path: /static/file/**
      max-file-size: 20MB
      max-part-size: 10MB
      max-big-file-size: 1GB


spring:
  quartz:
    # 任务存储类型
    job-store-type: memory
    # 关闭时等待任务完成
    wait-for-jobs-to-complete-on-shutdown: false
    # 是否覆盖已有的任务
    overwrite-existing-jobs: true
    # 是否自动启动计划程序
    auto-startup: true
    # 延迟启动
    startup-delay: 0s
    properties:
      org:
        quartz:
          scheduler:
            # 调度器实例名称
            instanceName: RainbowTask
          # 线程池配置
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
  flyway:
    # 开启 flyway
    enabled: true
    # 是否禁用数据库清理
    clean-disabled: true
    # SQL 迁移的编码
    encoding: UTF-8
    # 是否在执行迁移时自动调用验证。
    validate-on-migrate: true
    # 迁移时发现目标schema非空，而且带有没有元数据的表时，是否自动执行基准迁移，默认false.
    baseline-on-migrate: true
