// BRANCH=main
// APP_VERSION=1.0.0
// JASYPT_ENCRYPTOR_PASSWORD=
// RAINBOW_FILE_DOMAIN=http://127.0.0.1:5121/api
// PROFILES=prod
def LAST_BUILD_NUMBER = env.BUILD_NUMBER.toInteger() - 1
pipeline {
    agent any
  environment {
    APP_NAME = "ticho-rainbow-app"
    APP_PORT = "5122"
    DATASOURCE_URL = "jdbc:mysql://192.168.243.138:10032/ticho_rainbow?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowMultiQueries=true"
    DATASOURCE_USERNAME = "ENC(8yUwi7gFsHhtfKcuEHa6Kg==)"
    DATASOURCE_PASSWORD = "ENC(7xqTr9Bm6d2RCeaWdwMGlugy9f3P9sAK)"
    GIT_URL = "https://gitee.com/zhajianjun/ticho-rainbow.git"
    REGISTRY = "registry.cn-hangzhou.aliyuncs.com"
    IMGAGE_NAME = "${REGISTRY}/ticho/${APP_NAME}:${APP_VERSION}"
    DOCKFILE = "${APP_NAME}/deploy/Dockerfile"
    MAVEN_HOME = '/var/jenkins_home/maven/maven3.9.6'
    MAVEN_XML =  '/var/jenkins_home/maven/setting.xml'
    JAVA_HOME = '/var/jenkins_home/jdk/jdk8'
    PATH = "${env.PATH}:$JAVA_HOME/bin:$MAVEN_HOME/bin"
  }
  stages {
    stage('初始化工作空间') {
            steps {
                script {
                    deleteDir()
                }
            }
    }
    stage("拉取代码") {
      steps {
        git(credentialsId: "gitee", url: "${GIT_URL}", branch: "${BRANCH}", changelog: true, poll: false)
      }
    }

    stage("应用编译") {
      steps {
        sh "mvn -U -s ${MAVEN_XML}  -Dmaven.test.skip=true clean package -P rdc"
      }
    }

    stage("应用制品") {
      steps {
        archiveArtifacts "**/target/*.jar"
      }
    }

    stage("构建容器镜像") {
      steps {
        sh "docker build -f ${DOCKFILE} -t ${IMGAGE_NAME} ."
      }
    }

    stage("推送镜像") {
      steps {
        withCredentials([usernamePassword(credentialsId : "aliyun-registry" ,usernameVariable : "DOCKER_USERNAME" ,passwordVariable : "DOCKER_PASSWORD" ,)]) {
          sh "docker login registry.cn-hangzhou.aliyuncs.com -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}"
          sh "docker push ${IMGAGE_NAME}"
        }
      }
    }

    stage("应用部署") {
      steps {
          script {
            def result = sh(script: "docker rm -f ${APP_NAME}", returnStatus: true)
            if (result != 0) {
                echo '${APP_NAME}容器不存在'
            }
          }
        sh "docker run -itd \
            --name ${APP_NAME} \
            -e PROFILES='${PROFILES}' \
            -e DATASOURCE_URL='${DATASOURCE_URL}' \
            -e DATASOURCE_USERNAME='${DATASOURCE_USERNAME}' \
            -e DATASOURCE_PASSWORD='${DATASOURCE_PASSWORD}' \
            -e RAINBOW_FILE_DOMAIN='${RAINBOW_FILE_DOMAIN}' \
            -e JASYPT_ENCRYPTOR_PASSWORD='${JASYPT_ENCRYPTOR_PASSWORD}' \
            -p ${APP_PORT}:${APP_PORT} \
            -v /data:/data \
            --restart always \
            ${IMGAGE_NAME}"
        script {
            def result = sh(script: "docker rmi -f ${LAST_IMGAGE_NAME}", returnStatus: true)
            if (result != 0) {
                echo '${LAST_IMGAGE_NAME}镜像不存在'
            }
        }
      }
    }
  }
}